package enums;

public enum Constant {
	SCENE_WIDTH(600),
	SCENE_HEIGHT(337),
	JET_SPEED(0.3),
	JET_WIDTH(27),
	JET_HEIGHT(9),
	MISSILE_WIDTH(11),
	MISSILE_HEIGHT(5),
	MISSILE_RANGE(20),
	CLUSTER_WIDTH(11),
	CLUSTER_HEIGHT(5),
	BOMBLET_WIDTH(5),
	BOMBLET_HEIGHT(3),
	BOMBLET_RANGE(10),
	NUKE_WIDTH(14),
	NUKE_HEIGHT(7),
	NUKE_RANGE(100),
	BOMB_ACCELERATION(0.0005),
	MISSILE_EXPLOSION_WIDTH(68),
	MISSILE_EXPLOSION_HEIGHT(61),
	BOMBLET_EXPLOSION_WIDTH(15),
	BOMBLET_EXPLOSION_HEIGHT(14),
	JET_EXPLOSION_WIDTH(30),
	JET_EXPLOSION_HEIGHT(30),
	TRUCK_WIDTH(36),
	TRUCK_HEIGHT(17),
	TRUCK_SPEED(0.1),

	TANK_WIDTH(32),
	TANK_HEIGHT(16),
	TANK_SPEED(0.1),
	ATTACK_TANK_WIDTH(32),
	ATTACK_TANK_HEIGHT(17),
	ATTACK_TANK_SPEED(0.1),
	ATTACK_TANK_RANGE(100),
	MIG_WIDTH(32),
	MIG_HEIGHT(16),
	MIG_SPEED(0.1),
	MIG_RANGE(100),
	TREE_WIDTH(18),
	TREE_HEIGHT(35),
	BASE_WIDTH(48),
	BASE_HEIGHT(40),
	BUNKER_WIDTH(48),
	BUNKER_HEIGHT(40),
	EARTH_WIDTH(600),
	EARTH_HEIGHT(38),
	FIRE_WIDTH(20),
	FIRE_HEIGHT(25),
	ATTACKING_BOMB_WIDTH(5),
	ATTACKING_BOMB_HEIGHT(3),
	ATTACKING_BOMB_SPEED(0.1),
	NUKE_BONUS_WIDTH(28),
	NUKE_BONUS_HEIGHT(28),
	NUKE_BONUS_SPEED(0.05),
	CLUSTER_BONUS_WIDTH(28),
	CLUSTER_BONUS_HEIGHT(28),
	CLUSTER_BONUS_SPEED(0.05);

	private final double value;

	Constant(double value) {
		this.value = value;
	}

	public double getValue() {
		return value;
	}
}
